[package]
name = "md_feed"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
hdrhistogram = "7.5"
quanta = "0.12"
coarsetime = "0.1"
core_affinity = "0.8"
ringbuf = "0.4.8"
tokio = { version = "1", features = ["full"] }
tokio-tungstenite = { version = "0.21", features = ["rustls-tls-webpki-roots"] }
tungstenite = { version = "0.21", features = ["rustls-tls-webpki-roots"] }
anyhow = "1.0.100"
tracing = "0.1.41"
tracing-subscriber = {version = "0.3.20", features = ["env-filter"]}
log = "0.4.28"
env_logger = "0.11.8"
fast-float = "0.2.0"
lexical = "6.1"
thiserror = "2.0.17"
serde_json = { version="1", features=["preserve_order"] }
futures-util = "0.3"
async-trait = "0.1.89"
iceoryx2 = "0.7.0"
ethers = { version = "2", features = ["eip712"] }
rmp-serde = "1"
tiny-keccak = { version = "2", features = ["keccak"] }
hex = "0.4"
reqwest = {version = "0.12.26", features = ["blocking", "json"] }
serde_yaml = "0.9"
ratatui = "0.28"
crossterm = "0.28"
arc-swap = "1.7"

[lib]
name = "md_feed"
path = "src/lib.rs"

[[bin]]
name = "main"
path = "src/main.rs"

[[bin]]
name = "aeron_publisher"
path = "src/examples/aeron_publisher.rs"

[[bin]]
name = "paradex_ws_example"
path = "src/examples/paradex_ws_example.rs"

[[bin]]
name = "hyperliquid_publisher"
path = "src/examples/hyperliquid_publisher.rs"

[[bin]]
name = "engine_demo"
path = "src/examples/engine_demo.rs"

[[bin]]
name = "ts_demo"
path = "src/examples/ts_demo.rs"

[[bin]]
name = "ts_runner_demo"
path = "src/examples/ts_runner_demo.rs"

[[bin]]
name = "ts_cli"
path = "src/examples/ts_cli.rs"
